name: twelfth_mobile
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  material_symbols_icons: ^4.2719.0
  flutter_svg: ^2.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard.ttf
          weight: 400
        - asset: assets/fonts/Pretendard.ttf
          weight: 600

  assets:
    - assets/images/
